header:
    title: Welcome to my class!
    text: It's Nice To Meet You
    button: Interviewing Course
    buttonlink: "#services" # "#{section}" or "URL/page link"

services:
    title: "Services"
    text: "Lorem ipsum"
    section: services
    list:
      - title: "Data Structures"
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
        icon: fas fa-shopping-cart #find more at https://fontawesome.com/icons
      - title: "Algorithms"
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
        icon: fas fa-laptop       
      - title: "Communication"
        desc: "Your description here, full **Markdown** support"
        icon: fab fa-markdown

portfolio:
    title: "Courses"
    text: "We offer courses to take you to the offer and beyond"
    section: portfolio
    

timeline:
    title: "About" 
    text: "Ali's journey in CS"
    section: timeline
    events:
      - title: "Humble Beginnings"
        year: "Fall 2019"
        desc: "Intered at a local company, simplepart, part time while I was in college. I learned basic development skills here."
        image: assets/img/timeline/1.jpg
        alt: 
        align: left
      - title: " Research institute "
        year: "Summer 2020"
        desc: "Interned at a research institute GTRI, built a website using angular and javascript."
        image: assets/img/timeline/2.jpg
        alt: 
        align: right
      - title: "Interned at a tech company, UKG (ultimte software) "
        year: "Fall 2020"
        desc: "Went further into web development, and started interview preparation on DS/A topics"
        image: assets/img/timeline/2.jpg
        alt: 
        align: right
      - title: "FAANG"
        year: "Summer 2021"
        desc: "Got multiple high paying offers from Amazon, Capital One, and others for summer 2021. Now my goal is to help you get the same thing!"
        image: assets/img/timeline/3.jpg
        alt: image alt text
        #align: #default is left       
    end: "Make <br> YOUR <br> Story!"

about:
    title: "About Me"
    text: "My story"
    section: about
    
team:
    title: "OUR AMAZING TEAM"
    text: "Lorem ipsum dolor sit amet consectetur."
    subtext: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde. **Markdown** supported.
    section: team
    people:
      - name: "Ali Kazmi"
        role: "Instructor"
        image: assets/img/team/2.jpg
        social:
          - url: https://linkedin.com/in/alirkazmi
            icon: fab fa-linkedin-in
          
contact:
    title: "Contact Us"
    text: "Lorem ipsum or call 123456789"
    section: contact
    
footer:
    legal: "Privacy Policy"
    social:
      - url: https://linkedin.com/in/alirkazmi
        icon: "fab fa-linkedin-in"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
